version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
