name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout Github Actions'
        uses: actions/checkout@v2
      - name: 'Login to Github Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and Push the image'
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/hello:latest  # Build the new image
          docker push ghcr.io/${{ github.repository_owner }}/hello:latest  # Push the new image to GHCR

  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    needs: push-to-ghcr  # Ensures DemoSonarCloudScan runs after the image is pushed
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Use the pre-built image (the one we just built and pushed)
      - name: 'Login to Github Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Pull the newly built image'
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/hello:latest  # Pull the newly built image

      # Set up Python, install dependencies, and run tests
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov  # Install pytest and coverage tools

      - name: 'Run tests and generate coverage report'
        run: |
          pytest --cov=./ --cov-report=xml:coverage.xml  # Run tests and generate coverage report in XML format

      - name: 'SonarCloud Scan'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mona-13
            -Dsonar.projectKey=mona-13
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Path to the coverage file
